### ISSUE TITLE
Space not working in web

### ISSUE THREAD

**Issue by true2thepen** [CodoPixel/code_editor#1]
When running the project for web the spacebar does not work. However shift+spacebar does. This is very inconvenient. It works properly on Android and Linux. As I, currently do not have any Apple products I can not test this on them. If/when I get a chance I might test it on Windows. I intend on using this and would very much like it to work on web.

Addition:
Seems to be a problem with SingleChildScrollView. Swapping it out for Container seems to solve the no spacebar on web issue. However, this isn't a viable solution as it causes overflow on Android.

**Comment by ThomasGysemans** [comment]
Hi, since the last version of code_editor, I have had very little time to keep the project up to date, time which I have given to other projects and personal studies, and so I sincerely apologise for the delay in responding.

Recently, I decided to get back into it because I saw that a lot of people were interested in the project.

A lot of changes have been made to the code to make it compatible with Flutter 2.0. Since these changes, I took the time to test code_editor on the web and I think the issue has been solved.

I hope my project will help you in designing your own.
